#!/usr/bin/env python3
import argparse
from nixipfs.create_channel_release import create_channel_release
from nixipfs.defaults import *

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Fetch a jobset from a Hydra')
    parser.add_argument('--channel', required=True, type=str)
    parser.add_argument('--hydra', default=DEFAULT_HYDRA, type=str)
    parser.add_argument('--project', required=True, type=str)
    parser.add_argument('--jobset', required=True, type=str)
    parser.add_argument('--cache', default=DEFAULT_BINARY_CACHE_URL, type=str)
    parser.add_argument('--target_cache', default=DEFAULT_BINARY_CACHE_URL, type=str)
    parser.add_argument('--outdir', required=True, type=str)
    parser.add_argument('--tmpdir', default='.', type=str)
    args = parser.parse_args()
    ret = create_channel_release(channel=args.channel, hydra=args.hydra, project=args.project, jobset=args.jobset,
                                 cache=args.cache, outdir=args.outdir, tmpdir=args.tmpdir, target_cache=args.target_cache)
    print(ret)
